
# DO NOT DELETE

base85.o: base85ed.h
base85ed.o: base85ed.h
base85ed_test.o: /usr/include/gtest/gtest.h
base85ed_test.o: /usr/include/gtest/gtest-assertion-result.h
base85ed_test.o: /usr/include/gtest/gtest-message.h
base85ed_test.o: /usr/include/gtest/internal/gtest-port.h
base85ed_test.o: /usr/include/ctype.h /usr/include/features.h
base85ed_test.o: /usr/include/features-time64.h /usr/include/stdc-predef.h
base85ed_test.o: /usr/include/stdio.h /usr/include/stdlib.h
base85ed_test.o: /usr/include/alloca.h /usr/include/string.h
base85ed_test.o: /usr/include/strings.h
base85ed_test.o: /usr/include/gtest/internal/custom/gtest-port.h
base85ed_test.o: /usr/include/gtest/internal/gtest-port-arch.h
base85ed_test.o: /usr/include/unistd.h /usr/include/regex.h
base85ed_test.o: /usr/include/gtest/gtest-death-test.h
base85ed_test.o: /usr/include/gtest/internal/gtest-death-test-internal.h
base85ed_test.o: /usr/include/gtest/gtest-matchers.h
base85ed_test.o: /usr/include/gtest/gtest-printers.h
base85ed_test.o: /usr/include/gtest/internal/gtest-internal.h
base85ed_test.o: /usr/include/gtest/internal/gtest-filepath.h
base85ed_test.o: /usr/include/gtest/internal/gtest-string.h
base85ed_test.o: /usr/include/gtest/internal/gtest-type-util.h
base85ed_test.o: /usr/include/gtest/internal/custom/gtest-printers.h
base85ed_test.o: /usr/include/gtest/gtest-param-test.h
base85ed_test.o: /usr/include/gtest/internal/gtest-param-util.h
base85ed_test.o: /usr/include/gtest/gtest-test-part.h
base85ed_test.o: /usr/include/gtest/gtest-typed-test.h
base85ed_test.o: /usr/include/gtest/gtest_pred_impl.h
base85ed_test.o: /usr/include/gtest/gtest_prod.h base85ed.h
